import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Bell, Banknote, LogOut } from 'lucide-react'
import { api, clearSession, getCachedUser } from '../lib/api.js'
import PageHeader from '../components/PageHeader.jsx'
import Button from '../components/Button.jsx'
function Toggle({checked,onChange,label}){return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)} className={`relative w-12 h-7 rounded-full shrink-0 ${checked?'bg-growth-500':'bg-cloud-300'}`}><span className={`absolute top-0.5 left-0.5 w-6 h-6 rounded-full bg-white shadow ${checked?'translate-x-5':''}`}/></button>}
function SettingRow({icon:Icon,chip,title,body,children}){return <div className="flex items-center gap-4 py-4"><div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${chip}`}><Icon size={20}/></div><div className="flex-1 min-w-0"><p className="font-medium text-trust-700">{title}</p><p className="text-sm text-trust-400">{body}</p></div>{children}</div>}
export default function Settings(){
 const navigate=useNavigate(),cached=getCachedUser(),[user,setUser]=useState(cached),[jobAlerts,setJobAlerts]=useState(cached?.notificationPrefs?.jobAlerts!==false),[paymentAlerts,setPaymentAlerts]=useState(cached?.notificationPrefs?.paymentAlerts!==false),[confirming,setConfirming]=useState(false)
 useEffect(()=>{api.me().then(d=>{setUser(d.user);setJobAlerts(d.user.notificationPrefs?.jobAlerts!==false);setPaymentAlerts(d.user.notificationPrefs?.paymentAlerts!==false)})},[])
 async function update(key,val){if(key==='job')setJobAlerts(val);else setPaymentAlerts(val);await api.settings(key==='job'?{jobAlerts:val}:{paymentAlerts:val})}
 function logOut(){clearSession();navigate('/',{replace:true})}
 if(!user)return null
 return <div className="max-w-lg"><PageHeader title="Settings" subtitle="Manage your account and notifications."/><div className="bg-white rounded-2xl border border-trust-100/70 shadow-card p-5 mb-4 flex items-center gap-4"><div className="w-14 h-14 rounded-full bg-gradient-to-br from-trust-100 to-growth-100 flex items-center justify-center font-display font-bold text-xl text-trust-700">{user.name.split(' ').map(n=>n[0]).join('')}</div><div><p className="font-display font-bold text-lg text-trust-700">{user.name}</p><p className="text-sm text-trust-400">Member since {user.memberSince}</p></div></div>
  <div className="bg-white rounded-2xl border border-trust-100/70 shadow-card px-5 mb-4 divide-y divide-cloud-200"><SettingRow icon={Bell} chip="bg-trust-50 text-trust-500" title="New jobs near me" body="Get alerted when tasks are posted close by."><Toggle checked={jobAlerts} onChange={v=>update('job',v)} label="New jobs near me"/></SettingRow><SettingRow icon={Banknote} chip="bg-growth-100 text-growth-600" title="Payment updates" body="Know when money reaches your wallet."><Toggle checked={paymentAlerts} onChange={v=>update('payment',v)} label="Payment updates"/></SettingRow></div>
  <div className="bg-white rounded-2xl border border-trust-100/70 shadow-card p-5">{!confirming?<><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-full bg-amber-500/10 text-amber-600 flex items-center justify-center shrink-0"><LogOut size={20}/></div><div><p className="font-medium text-trust-700">Log out</p><p className="text-sm text-trust-400">You'll need your phone number to sign back in.</p></div></div><Button variant="danger" size="lg" full onClick={()=>setConfirming(true)}>Log out</Button></>:<><p className="font-semibold text-trust-700">Log out of WorkLink?</p><p className="text-sm text-trust-400 mt-1 mb-4">Your wallet and profile stay safe.</p><div className="grid grid-cols-2 gap-3"><Button variant="soft" size="lg" onClick={()=>setConfirming(false)}>Cancel</Button><Button variant="primary" size="lg" onClick={logOut}>Log out</Button></div></>}</div><p className="text-center text-xs text-trust-300 mt-6">WorkLink v1.0 Railway</p></div>
}