import { useEffect, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight } from 'lucide-react'
import Button from '../components/Button.jsx'
import { api } from '../lib/api.js'
export default function Wallet(){
 const [data,setData]=useState({balance:0,earned:0,transactions:[]}),[show,setShow]=useState(false),[amount,setAmount]=useState(''),[accountRef,setAccountRef]=useState(''),[message,setMessage]=useState('')
 const load=()=>api.wallet().then(setData).catch(e=>setMessage(e.message)); useEffect(load,[])
 const earningsThisMonth=data.transactions.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0)
 async function withdraw(e){e.preventDefault();try{await api.withdraw({amount:Number(amount),method:'ewallet',accountRef});setMessage('Withdrawal requested.');setShow(false);setAmount('');load()}catch(e){setMessage(e.message)}}
 return <div><h1 className="text-2xl font-bold text-trust-700 mb-6">My Wallet</h1>
  <div className="bg-gradient-to-br from-trust-700 via-trust-700 to-trust-500 rounded-2xl p-6 text-white mb-6"><p className="text-trust-200 text-sm">Available balance</p><p className="font-display font-bold text-4xl mt-1">R{Number(data.balance).toFixed(2)}</p><div className="flex gap-3 mt-5"><Button onClick={()=>setShow(!show)} variant="custom" className="bg-white/15 text-white hover:bg-white/25 flex-1">Withdraw</Button></div></div>
  {show&&<form onSubmit={withdraw} className="bg-white rounded-2xl border border-trust-100/70 shadow-card p-5 mb-6 flex flex-col gap-3"><h2 className="font-semibold text-trust-700">Request withdrawal</h2><input required type="number" min="50" max={data.balance} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount (R)" className="rounded-xl border border-cloud-300 px-4 py-3"/><input required value={accountRef} onChange={e=>setAccountRef(e.target.value)} placeholder="eWallet / account reference" className="rounded-xl border border-cloud-300 px-4 py-3"/><Button type="submit" variant="primary">Request payout</Button></form>}
  {message&&<div className="mb-4 rounded-xl bg-growth-50 border border-growth-100 text-growth-600 p-3 text-sm">{message}</div>}
  <div className="bg-white rounded-2xl border border-trust-100/70 shadow-card p-5 mb-6"><p className="text-trust-400 text-sm">Earnings this month</p><p className="font-display font-bold text-2xl text-trust-700 mt-1">R{earningsThisMonth.toFixed(2)}</p><div className="flex items-end gap-1.5 h-20 mt-4">{[30,55,40,70,45,90,60].map((h,i)=><div key={i} className="flex-1 bg-growth-100 rounded-t-md" style={{height:`${h}%`}}/>)}</div></div>
  <h2 className="text-lg font-bold text-trust-700 mb-3">Recent Transactions</h2><div className="flex flex-col gap-2">{data.transactions.map(t=>{const positive=t.amount>0;return <div key={t.id} className="bg-white rounded-2xl border border-trust-100/70 shadow-card p-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-full flex items-center justify-center ${positive?'bg-growth-50 text-growth-600':'bg-amber-500/10 text-amber-600'}`}>{positive?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</div><div><p className="font-medium text-trust-700">{t.label}</p><p className="text-xs text-trust-400">{t.date}</p></div></div><p className={`font-semibold ${positive?'text-growth-600':'text-amber-600'}`}>{positive?'+':''}R{Math.abs(t.amount).toFixed(2)}</p></div>})}</div>
 </div>
}